service: lambda-docker-template-api-public

plugins:
  - serverless-offline

provider:
  name: aws
  profile: default
  stage: dev
  region: ap-northeast-1
  memorySize: 2048
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:ListBucket'
          Resource:
            - "*"
        - Effect: 'Allow'
          Action:
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource:
            - "*"
        - Effect: Allow
          Action: 
            - 'ecr:*'
            - 'ecr-public:*'
            - 'sts:GetServiceBearerToken'
          Resource:
            - "*"
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: 'execute-api:Invoke'
        Resource: 'execute-api:/*/*/*'
    minimumCompressionSize: 1024
  environment:
    TZ: Asia/Tokyo
    ENV1: ${env:ENV1}
    ENV2: ${env:ENV2}

functions:
  api_endpoint1:
    image:
      uri:
        - ${env:IMAGE_URL}
      command:
        - api.endpoint1
    timeout: 30
    events:
      - http:
          path: api/v1/endpoint1
          method: get
          cors: true
    environment:
      HOGE1: 'hoge1'
  api_endpoint2:
    image:
      uri:
        - ${env:IMAGE_URL}
      command:
        - api.endpoint2
    timeout: 30
    events:
      - http:
          path: api/v1/endpoint2
          method: get
          cors: true
    environment:
      HOGE2: 'hoge2'
